
// Import the functions you need from the SDKs you need
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.8.3/firebase-app.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.8.3/firebase-analytics.js";
import { getFirestore, collection, addDoc, getDocs } from "https://www.gstatic.com/firebasejs/9.8.3/firebase-firestore.js"
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyDyaontRHzmZfRuKrnmszFVF5bblT8veig",
  authDomain: "basecaracterizacion.firebaseapp.com",
  projectId: "basecaracterizacion",
  storageBucket: "basecaracterizacion.appspot.com",
  messagingSenderId: "223851444302",
  appId: "1:223851444302:web:10a671a48da70fc8f76b1f",
  measurementId: "G-F5GEQL01TM"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

const db = getFirestore()
export const savetask = (nombreyapellidoBeneficiario,
  lugarnacimientoBeneficiario,
  fechanacimientoBeneficiario,
  tipoducmentoBeneficiario,
  numeroducmentoBeneficiario,
  generoBeneficiario,
  gruposanguineoBeneficiario,
  cursoBeneficiario,
  direccionBeneficiario,
  telefonoBeneficiario,
  celularBeneficiario,
  SisbenBeneficiario,
  seguridadsocialBeneficiario,
  redunidosBeneficiario,
  grupoetnico,
  victimaconflicto,
  padredesmovilizado,
  amenazadoreclutamiento,
  departamentoresidencia,
  municipioresidencia,
  zonaubicacionresidencia,
  direccionresidencia,
  barrioresidencia,
  tipodevivienda,
  tipodetendenciavivienda,
  tiempopermanecianucleocasa,
  numerodefamiliares,
  espaciosidependientescas,
  acueductocasa,
  energiacasa,
  gasnaturalcasa,
  telefonocasa,
  alcantarilladocasa,
  internetcasa,
  obtencionagua,
  usanelagua,
  elminabasura,
  sanitario,
  viasacceso,
  transportepublcio,
  sedeeducativa,
  ludoteca,
  centrosalud,
  parques,
  nombreyapellidocabezahogar,
  tipodecumentocabezahogar,
  numerodecumentocabezahogar,
  lugarnacimientocabezahogar,
  fechanacimientocabezahogar,
  direccioncabezahogar,
  barriocabezahogar,
  correoelectronicocabezahogar,
  telefonocabezahogar,
  celularcabezahogar,
  parentescocabezahogar,
  sabeleercabezahogar,
  sabeescribircabezahogar,
  primariacabezahogar,
  secundariacabezahogar,
  tecniciocabezahogar,
  tecnologicocabezahogar,
  universidadcabezahogar,
  conflictocabezahogar,
  desastrescabezahogar,
  discapacidadcabezahogar,
  condicionespecialcabezahogar,
  familiasaccioncabezahogar,
  estadolaboralcabezahogar,
  empeladocabezahogar,
  cargocabezahogar,
  empresacabezahogar,
  saldocabezahogar,
  entidadsaludcabezahogar,
  asosiacionescabezahogar,
  planeacionembarazo,
  nombreyapellidoacudente,
  tipodecumentoacudente,
  numerodecumentoacudente,
  lugarnacimientoacudente,
  fechanacimientoacudente,
  direccionacudente,
  barrioacudente,
  correoelectronicacudente,
  telefonoacudente,
  celularacudente,
  parentesacudente,
  conflictoacudiente,
  desastresacudiente,
  discapacidadacudiente,
  condicionespecialacudiente,
  aporteacudiente,
  saldoacudiente,
  dignosticonutrcion,
  desparacitacion,
  Fechadesparacitacion,
  afiliacionbeneficiario,
  beneficiarioregimen,
  entidadpromotoradesalud,
  saludoral,
  oftalmologicos,
  audicion,
  medicogeneral,
  problemassalud,
  cualproblemassalud,
  discapacidadbeneficiario,
  cualdiscapacidadbeneficiario,
  registrodiscapacidad,
  Psicosocial,
  severidadPsicosocial,
  cognitiva,
  severidadcognitiva,
  sensorialvisual,
  severidadsensorialvisual,
  sensorialauditiva,
  severidadsensorialauditiva,
  sensorialgusto,
  severidadsensorialgusto,
  movilidad,
  severidadmovilidad,
  ayudaotrapersona,
  severidadayudaotrapersona,
  rehabilitacion,
  frecuenciarehabilitacion,
  conflictobeneficiario,
  desastresbeneficiario,
  condicionespecialbeneficiario,
  pidecomida,
  presentacionpersonal,
  presentaolores,
  frecuenciaenfermedades,
  brotes,
  temeroso,
  interes,
  aislamiento,
  espacaactividades,
  agresivo,
  destructor,
  amistoso,
  comparte,
  fluidez,
  cuidamedio,
  juegatranquilo,
  tareas,
  observacion) => 

  addDoc(collection(db, 'task'), {
    nombreyapellidoBeneficiario,
    lugarnacimientoBeneficiario,
    fechanacimientoBeneficiario,
    tipoducmentoBeneficiario,
    numeroducmentoBeneficiario,
    generoBeneficiario,
    gruposanguineoBeneficiario,
    cursoBeneficiario,
    direccionBeneficiario,
    telefonoBeneficiario,
    celularBeneficiario,
    SisbenBeneficiario,
    seguridadsocialBeneficiario,
    redunidosBeneficiario,
    grupoetnico,
    victimaconflicto,
    padredesmovilizado,
    amenazadoreclutamiento,
    departamentoresidencia,
    municipioresidencia,
    zonaubicacionresidencia,
    direccionresidencia,
    barrioresidencia,
    tipodevivienda,
    tipodetendenciavivienda,
    tiempopermanecianucleocasa,
    numerodefamiliares,
    espaciosidependientescas,
    acueductocasa,
    energiacasa,
    gasnaturalcasa,
    telefonocasa,
    alcantarilladocasa,
    internetcasa,
    obtencionagua,
    usanelagua,
    elminabasura,
    sanitario,
    viasacceso,
    transportepublcio,
    sedeeducativa,
    ludoteca,
    centrosalud,
    parques,
    nombreyapellidocabezahogar,
    tipodecumentocabezahogar,
    numerodecumentocabezahogar,
    lugarnacimientocabezahogar,
    fechanacimientocabezahogar,
    direccioncabezahogar,
    barriocabezahogar,
    correoelectronicocabezahogar,
    telefonocabezahogar,
    celularcabezahogar,
    parentescocabezahogar,
    sabeleercabezahogar,
    sabeescribircabezahogar,
    primariacabezahogar,
    secundariacabezahogar,
    tecniciocabezahogar,
    tecnologicocabezahogar,
    universidadcabezahogar,
    conflictocabezahogar,
    desastrescabezahogar,
    discapacidadcabezahogar,
    condicionespecialcabezahogar,
    familiasaccioncabezahogar,
    estadolaboralcabezahogar,
    empeladocabezahogar,
    cargocabezahogar,
    empresacabezahogar,
    saldocabezahogar,
    entidadsaludcabezahogar,
    asosiacionescabezahogar,
    nombreyapellidoacudente,
    tipodecumentoacudente,
    numerodecumentoacudente,
    lugarnacimientoacudente,
    fechanacimientoacudente,
    direccionacudente,
    barrioacudente,
    correoelectronicacudente,
    telefonoacudente,
    celularacudente,
    parentesacudente,
    conflictoacudiente,
    desastresacudiente,
    discapacidadacudiente,
    condicionespecialacudiente,
    aporteacudiente,
    saldoacudiente,
    dignosticonutrcion,
    desparacitacion,
    Fechadesparacitacion,
    afiliacionbeneficiario,
    beneficiarioregimen,
    entidadpromotoradesalud,
    saludoral,
    oftalmologicos,
    audicion,
    medicogeneral,
    problemassalud,
    cualproblemassalud,
    discapacidadbeneficiario,
    cualdiscapacidadbeneficiario,
    registrodiscapacidad,
    Psicosocial,
    severidadPsicosocial,
    cognitiva,
    severidadcognitiva,
    sensorialvisual,
    severidadsensorialvisual,
    sensorialauditiva,
    severidadsensorialauditiva,
    sensorialgusto,
    severidadsensorialgusto,
    movilidad,
    severidadmovilidad,
    ayudaotrapersona,
    severidadayudaotrapersona,
    rehabilitacion,
    frecuenciarehabilitacion,
    conflictobeneficiario,
    desastresbeneficiario,
    condicionespecialbeneficiario,
    pidecomida,
    presentacionpersonal,
    presentaolores,
    frecuenciaenfermedades,
    brotes,
    temeroso,
    interes,
    aislamiento,
    espacaactividades,
    agresivo,
    destructor,
    amistoso,
    comparte,
    fluidez,
    cuidamedio,
    juegatranquilo,

  })


export const gettask = () => {
  getDocs(collection(db, 'task'))


}
